#!/bin/sh

ADDONNAME=brickd
CONFIG_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/${ADDONNAME}
RCD_DIR=${CONFIG_DIR}/rc.d

mount /usr/local || true

# create necessary directories
mkdir -p ${ADDON_DIR}
chmod 755 ${ADDON_DIR}
mkdir -p ${RCD_DIR}
chmod 755 ${RCD_DIR}

cp -af addon/* ${ADDON_DIR}
cp -af rc.d/* ${RCD_DIR}

chmod 775 ${ADDON_DIR}/brickd
chmod 775 ${RCD_DIR}/brickd

sync
